@startuml Spikylin Archtecture
actor user
user --> Angular
cloud VM{
    frame Angular{
        component angular_components
    }
    Angular <--> ASP.NET_Web_API : REST API
    frame ASP.NET_Web_API{
        rectangle controls
        rectangle services
        rectangle models
    }
}

cloud cloud{
    database MongoDB
}
MongoDB <--> ASP.NET_Web_API
@enduml
